### ISSUE TITLE
Instructions on how to fully uninstall

### ISSUE THREAD

**Issue by brorogans** [GalaxyPay/func#37]
How to stop and remove the app?

On a mac so far

`rm -rf /opt/func`

yet 

http://localhost:3536 is still populated with an unkillable process

**Comment by acfunk** [comment]
First kill the FUNC service, then you can `rm`  the files

```sh
launchctl kill 9 system/func.api
rm /Library/LaunchDaemons/func.api
rm -r /opt/func
```

If you stopped and removed the Node services through the UI and want to `rm` the node data too...

```sh
rm -r /usr/local/share/func
```

**Comment by brorogans** [comment]
Perfect, thanks for this
