### ISSUE TITLE
Request on Algorand: Optional 2 ALGO transaction fee when you register your participation keys online

### ISSUE THREAD

**Issue by BakaJaba** [GalaxyPay/func#39]
Hello there! Love the simplicity and ease of use of FUNC.

Could you look into this request feasability?

Doing so would mark the account as “incentive-eligible”, for rewards gatherers of the block producing world.

Thanks & happy everything

Cheers!

**Comment by BakaJaba** [comment]
Well you already answered me on reddit didn't you.

Thanks again for everything!

**Comment by acfunk** [comment]
I'll leave this open even though it won't be implemented until incentives are live on MainNet.

**Comment by acfunk** [comment]
This is implemented in #40 (version 3.x) but the code will be inactive until incentives are live.
